### ISSUE TITLE
Google Drive Login error

### ISSUE THREAD

**Issue by whhdxl** [JimSeker/googleplayAPI#2]
Hello, I’m a Chinese student. Recently I’m writing a demo.  I want to request the user’s Google Drive file. So I integrated Gogole’s official code and found that I can’t log in successfully. Then I saw your code. I am very happy, but what is helpless is that your code is the same as the official one and you cannot log in successfully. After I select the user to log in, the page that prompts the user for authorization is always loading, and no exception is thrown in logcat. I have ruled out network factors, and enabled Drive API in the API Console, and established an OAuth 2.0 credential for Android. Can you tell me how I should do next？

**Comment by JimSeker** [comment]
Are you able to just login with google (not the google drive part) and complete it?
